migManager:
  config:
    name: custom-mig-config
    create: true
    data: |-
      all-disabled:
        - devices: all
          mig-enabled: false
      five-1g-one-2g:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.10gb": 5
            "2g.20gb": 1
